# setup webservers
---
  - hosts: server1:server2
    become: true
      tasks: 
        - name: update all
          apt: name=* state=latest
      gather_facts: no

become: true
tasks:
  - name: create new index.html file
    lineinfile:
      create: yes
      path: "{{ index_path }}"
      line: "<html> {{ Heylo }} </html>"
    notify: start apache

handlers:
  - name: start apache
  service: name=apache2 state=started